[package]
name = "upload-pokemon-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
csv = "1.2.2"
ksuid = "0.2.0"
serde = { version = "1.0.188", features = ["derive"] }
